class UniformMotion:
    initial_position: float
    velocity: float
    def __init__(self, initial_position: float, velocity: float) -> None: ...
    def position_at_time(self, time: float) -> float: ...
    def distance_traveled(self, time: float) -> float: ...
    def __repr__(self) -> str: ...

class UniformAcceleratedMotion:
    initial_position: float
    initial_velocity: float
    acceleration: float
    def __init__(
        self, initial_position: float, initial_velocity: float, acceleration: float
    ) -> None: ...
    def position_at_time(self, time: float) -> float: ...
    def velocity_at_time(self, time: float) -> float: ...
    def __repr__(self) -> str: ...
