class Vector2:
    x: float
    y: float

    def __init__(self, x: float, y: float) -> None: ...
    def __add__(self, other: Vector2) -> Vector2: ...
    def __sub__(self, other: Vector2) -> Vector2: ...
    def __mul__(self, scalar: float) -> Vector2: ...
    def __truediv__(self, scalar: float) -> Vector2: ...
    def magnitude(self) -> float: ...
    def dot(self, other: Vector2) -> float: ...
    def __repr__(self) -> str: ...
